module.exports = {
  GET_DEPARTMENTS: 'GET_DEPARTMENTS',
  GET_LOCATIONS: 'GET_LOCATIONS',
  GET_EMPLOYEES: 'GET_EMPLOYEES',
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
  EMPLOYEE_ERROR: 'DELETE_EMPLOYEE_ERROR',
  ADD_EMPLOYEE: 'ADD_EMPLOYEE',
  CURRENT_EMPLOYEE: 'CURRENT_EMPLOYEE',
  EDIT_EMPLOYEE: 'EDIT_EMPLOYEE'
}
